/*

##     ## ##    ## ##     ##  ######  ######## ########  
##     ## ###   ## ##     ## ##    ## ##       ##     ## 
##     ## ####  ## ##     ## ##       ##       ##     ## 
##     ## ## ## ## ##     ##  ######  ######   ##     ## 
##     ## ##  #### ##     ##       ## ##       ##     ## 
##     ## ##   ### ##     ## ##    ## ##       ##     ## 
 #######  ##    ##  #######   ######  ######## ########  

*/
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class InitializePlayers extends javax.swing.JFrame {

    private ArrayList<String> playerNames;
    
    public InitializePlayers() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (UnsupportedLookAndFeelException | ClassNotFoundException |
                InstantiationException | IllegalAccessException e) {
        }
        
        initComponents();
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        startButton.setEnabled(false);
        playerNames = new ArrayList<String>();
    }
    
    public ArrayList<String> getPlayerNames(){
        return playerNames;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        playersTitle = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        playerPanel = new javax.swing.JPanel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        playerName1 = new javax.swing.JLabel();
        playerName2 = new javax.swing.JLabel();
        playerName3 = new javax.swing.JLabel();
        playerName4 = new javax.swing.JLabel();
        playerName5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(768, 576));
        setResizable(false);

        panel.setBackground(java.awt.Color.white);
        panel.setPreferredSize(new java.awt.Dimension(768, 576));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playersTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        playersTitle.setText("Players");
        playersTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playersTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(playersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        nameBox.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        nameBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameBox.setToolTipText("null");
        nameBox.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua", 0, 13))); // NOI18N
        panel.add(nameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 272, -1));

        addButton.setBackground(new java.awt.Color(81, 150, 87));
        addButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        addButton.setText("Add");
        addButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        panel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 272, 62));

        startButton.setBackground(new java.awt.Color(199, 91, 57));
        startButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        startButton.setText("START");
        startButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        panel.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 272, 62));

        playerPanel.setBackground(new java.awt.Color(255, 187, 147));
        playerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        p1.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        p1.setForeground(new java.awt.Color(81, 150, 87));
        p1.setText("P1");

        p2.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        p2.setForeground(new java.awt.Color(81, 150, 87));
        p2.setText("P2");

        p3.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        p3.setForeground(new java.awt.Color(81, 150, 87));
        p3.setText("P3");

        p4.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        p4.setForeground(new java.awt.Color(81, 150, 87));
        p4.setText("P4");

        p5.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        p5.setForeground(new java.awt.Color(81, 150, 87));
        p5.setText("P5");

        playerName1.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N

        playerName2.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N

        playerName3.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N

        playerName4.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N

        playerName5.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addComponent(p1)
                        .addGap(18, 18, 18)
                        .addComponent(playerName1))
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addComponent(p2)
                        .addGap(18, 18, 18)
                        .addComponent(playerName2))
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addComponent(p5)
                        .addGap(18, 18, 18)
                        .addComponent(playerName5))
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addComponent(p3)
                        .addGap(18, 18, 18)
                        .addComponent(playerName3))
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addComponent(p4)
                        .addGap(18, 18, 18)
                        .addComponent(playerName4)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1)
                    .addComponent(playerName1))
                .addGap(18, 18, 18)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerName2)
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addComponent(p2)
                        .addGap(18, 18, 18)
                        .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerName3)
                            .addComponent(p3))))
                .addGap(18, 18, 18)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerName4)
                    .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerName5)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220))
        );

        panel.add(playerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 320, 320));

        jButton1.setBackground(new java.awt.Color(199, 91, 57));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 272, 62));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (nameBox.getText().isEmpty()) {
            JLabel message = new JLabel("Please enter a name!");
            message.setFont(new Font("Perpetua", Font.PLAIN, 24));
            JOptionPane.showMessageDialog(null, message);
        } else {
            
            String name = nameBox.getText().trim();
            playerNames.add(name);
            
            switch (playerNames.size()) {
                case 1:
                    p1.setVisible(true);
                    playerName1.setText(playerNames.get(0));
                    break;
                case 2:
                    p2.setVisible(true);
                    playerName2.setText(playerNames.get(1));
                    break;
                case 3:
                    p3.setVisible(true);
                    playerName3.setText(playerNames.get(2));
                    break;
                case 4:
                    p4.setVisible(true);
                    playerName4.setText(playerNames.get(3));
                    break;
                case 5:
                    p5.setVisible(true);
                    playerName5.setText(playerNames.get(4));
                    addButton.setEnabled(false);
                    break;
            }
            
            nameBox.setText("");
            
            if (playerNames.size() > 0) {
                startButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new BlackjackUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        new StartGame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitializePlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nameBox;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel playerName1;
    private javax.swing.JLabel playerName2;
    private javax.swing.JLabel playerName3;
    private javax.swing.JLabel playerName4;
    private javax.swing.JLabel playerName5;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JLabel playersTitle;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
